<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.5.16</version>
    <relativePath />
  </parent>

  <groupId>cn.nanpo</groupId>
  <artifactId>nanpo-window</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>Nanpo Window</name>

  <modules>
    <module>backend</module>
  </modules>

  <properties>
    <java.version>21</java.version>
    <frontend-maven-plugin.version>2.0.1</frontend-maven-plugin.version>
    <node.version>v22.19.0</node.version>
    <node.download.root>https://npmmirror.com/mirrors/node/</node.download.root>
    <npm.registry>https://registry.npmmirror.com</npm.registry>
    <skip.frontend>false</skip.frontend>
  </properties>
</project>
