spring:
  application:
    name: nanpo-window
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1h

server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json,image/svg+xml

management:
  endpoints:
    web:
      exposure:
        include: health,info
