spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  auth:
    local-account-password: ${LOCAL_ACCOUNT_PASSWORD:}
  storage:
    type: ${STORAGE_TYPE:cos}

springdoc:
  api-docs:
    enabled: ${OPENAPI_ENABLED:false}
  swagger-ui:
    enabled: ${OPENAPI_ENABLED:false}
